dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-05-06 14:09:19.104184+00:00
  dag_id: scrapTheCutCoreOutreachWorkflows
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: adf
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: -NxDEBp84x3ag8M_4MAR
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 10 8 5 4 *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  trigger_url: https://httpbin.org/get
  trigger_url_expected_response: https://httpbin.org/get
  updated_at: 2024-05-06 14:09:19.104267+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-05-06 14:09:09.867690+00:00
  data:
    chain: true
    index: 0
    query:
    - psychologistswithoutborders
    round: 123
  deleted_at: null
  endpoint: instagram/scrapUsers/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NxDE9Zd25adLeV_4c6f
  log_response: true
  method: POST
  response_check: ''
  task_id: getUsers
  updated_at: 2024-05-06 14:09:09.867763+00:00
  urls: null
  xcom_push: false
- created_at: 2024-05-06 14:09:12.224238+00:00
  data:
    accounts: 18
    chain: true
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 123
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NxDEA8woYiIiHDpzCOq
  log_response: true
  method: POST
  response_check: ''
  task_id: getInfo
  updated_at: 2024-05-06 14:09:12.224299+00:00
  urls: null
  xcom_push: false
- created_at: 2024-05-06 14:09:13.935776+00:00
  data:
    chain: true
    keywords_to_check:
    - psychologists
    round: 123
  deleted_at: null
  endpoint: instagram/insertAndEnrich/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NxDEAZZCIA-11GrpxOr
  log_response: true
  method: POST
  response_check: ''
  task_id: enrich
  updated_at: 2024-05-06 14:09:13.935819+00:00
  urls: null
  xcom_push: false
- created_at: 2024-05-06 14:09:15.627870+00:00
  data:
    chain: true
    index: 0
    round: 123
  deleted_at: null
  endpoint: instagram/getAccounts/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NxDEAyoGdxVpgJU0AZj
  log_response: true
  method: POST
  response_check: ''
  task_id: getAccounts
  updated_at: 2024-05-06 14:09:15.627911+00:00
  urls: null
  xcom_push: false
- created_at: 2024-05-06 14:09:17.327972+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NxDEBOUgGgE4YVs9vsl
  log_response: true
  method: POST
  response_check: ''
  task_id: reactToStory
  updated_at: 2024-05-06 14:09:17.328043+00:00
  urls:
  - '{"set_of_urls": [{"url": "https://mqtt.booksy.us.boostedchat.com/like", "delay":
    105}, {"url": "https://mqtt.booksy.us.boostedchat.com/comment", "delay": 60}],
    "round": 1, "delay": 24}'
  - '{"set_of_urls": [{"conditional_url": "https://api.booksy.us.boostedchat.com/v1/instagram/has-client-responded/"},
    {"url": "https://mqtt.booksy.us.boostedchat.com/reactToStory", "delay": 230}],
    "round": 2, "delay": 24}'
  - '{"set_of_urls": [{"conditional_url": "https://api.booksy.us.boostedchat.com/v1/instagram/has-client-responded/"},
    {"url": "https://mqtt.booksy.us.boostedchat.com/like", "delay": 105}], "round":
    3, "delay": 24}'
  xcom_push: true
trigger_url: https://httpbin.org/get
trigger_url_expected_response: https://httpbin.org/get
